---
- yum_repository:
    file: mongodb-org-3.2
    name: mongodb-org-3.2
    description: mongodb-org-3.2
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-3.2.asc

- shell: yum makecache

- yum:
    name: mongodb-org
    state: present

- service:
    name: mongod
    state: restarted
    enabled: yes
