---
- hosts: deploy
  become: yes
  become_method: su
  tags: fresh_install
  roles:
    - common

- hosts: cluster
  become: yes
  become_method: su
  tags: cluster
  roles:
    - kubernetes

- hosts: app
  become: yes
  become_method: su
  tags: app_deploy
  roles:
    - ansible
#    - python3
    - docker
#    - cobbler
#    - lxc
#    - sqlite
#    - pgsql
#    - mysql
#    - mongodb
#    - rabbitmq
#    - redis

- hosts: web_test
  become: yes
  become_method: su
  tags: web_test
  roles:
#    - selenium
    - robotframework

- hosts: my_config
  become: no
  tags: my_config
  gather_facts: no
  roles:
    - my_config

