---
# handlers file for common
- name: update locate db
  shell: updatedb

- name: restart gpm
  service:
    name: gpm
    state: restarted
    enabled: yes

- name: restart sshd
  service:
    name: sshd
    state: restarted
    enabled: yes

- name: yum makecache
  shell: yum makecache
