---
- name: update locate db
  shell: updatedb

- name: restart sshd
  service: 
    name: sshd
    state: restarted
    enabled: yes

- name: yum makecache
  shell: yum makecache

- name: setup releasever
  command:  echo 7 > /etc/yum/vars/releasever
