---
- apt:
    update_cache: yes
    cache_valid_time: 3600

- apt:
    name:
      - lxc
      - lxc-templates
      - wget
      - bridge-utils
      - yum
    install_recommends: yes
    allow_unauthenticated: yes
    state: present
