---
- fail: 
    msg: OS don't support
  when:
    - ansible_distribution not in os_distro

- include: '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'

- name: update sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: ^UseDNS\s.*
    line: UseDNS yes
    backup: yes
  notify:
    - restart sshd

- meta: flush_handlers

- file:
    path: ~/.ssh
    state: directory
    mode: 0700
    backup: yes

- file:
    path: ~/.ssh/authorized_keys
    state: touch
    backup: yes

- name: add public key
  lineinfile:
    dest: ~/.ssh/authorized_keys
    line: '{{ public_key }}'
    mode: 0600
  when:
    - public_key is defined
