---
- yum_repository:
    file: RHEL
    name: RHEL
    description: RHEL
    baseurl: '{{ repo_url }}'
    gpgcheck: no
  when:
    - repo_url is defined
  notify:
    - yum makecache

- template:
    src: releasever.j2
    dest: /etc/yum/vars/releasever
    mode: 0444
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '7'

- shell: yum makecache

- yum_repository:
    file: '{{ item.file }}'
    name: '{{ item.name}}'
    description: '{{ item.description }}'
    mirrorlist: '{{ item.mirrorlist }}'
    gpgcheck: no
  with_items: '{{ centos7_repo }}'
  when:
    - ansible_distribution == 'RedHat'
    - ansible_distribution_major_version == '7'
  notify:
    - yum makecache

- yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- yum:
    name: "{{ item }}"
    state: installed
  notify:
    - update locate db
    - restart gpm
  with_items: '{{ redhat_packages }}'

#- yum:
#    name: "{{ item }}"
#  with_items:
#    - python2-pip
#    - bash-completion
#    - bash-completion-extras
#    - mlocate
#    state: installed
#  notify:
#    - update locate db
#
#- yum:
#    name:
#      - python2-pip
#      - bash-completion
#      - bash-completion-extras
#      - mlocate
#    state: installed
#  notify:
#    - update locate db

- name: update selinux config
  lineinfile:
    dest: /etc/selinux/config 
    regexp: ^SELINUX=.*
    line: SELINUX=disabled
    backup: no
  register: selinux_config

- name: reboot system
  shell: sleep 2 && shutdown -r now "ansible trigger to reboot"
  async: 1
  poll: 0
  ignore_errors: true
  when: selinux_config.changed

- name: wait for system come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=3
      timeout={{ reboot_time }}
      state=started
  ignore_errors: true
  when: selinux_config.changed
