---
- zypper_repository:
    name: SLES
    repo: '{{ repo_url }}'
    auto_import_keys: yes
  when:
    - repo_url is defined

- zypper_repository:
    name: '{{ item.name }}'
    repo: '{{ item.repo }}'
    auto_import_keys: yes
  with_items: '{{ opensuse42_2_repo }}'
  when:
    - ansible_distribution_version == '12.2'
    - opensuse42_2_repo is defined
 
- zypper:
    name: '{{ item }}'
    disable_recommends: no  
    state: present
  notify:
    - update locate db
  with_items: '{{ sles_packages }}'

