---
- apt:
    update_cache: yes
    cache_valid_time: 3600

- apt:
    name: docker.io
    state: present

- lineinfile:
    dest: /etc/default/docker
    regexp: ^DOCKER_OPTS=.*
    line: DOCKER_OPTS='--bip={{ docker_bip }} --storage-opt dm.loopdatasize={{ docker_data_size }} --storage-opt dm.loopmetadatasize={{ docker_meta_size }} --storage-opt dm.basesize={{ docker_base_size }}'
    backup: no
  notify:
    - stop service
    - rm docker_fodler
    - start service
